format_strings = true
format_macro_bodies = false
max_width = 80
merge_imports = true
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
report_fixme = "Always"
report_todo = "Always"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
comment_width = 65
empty_item_single_line = false
enum_discrim_align_threshold = 30
struct_field_align_threshold = 20
